<?php

namespace Drupal\camp_evaluator\Form;

use Drupal\Core\Entity\EntityForm;
use Drupal\Core\Form\FormStateInterface;

/**
 * Class EvaluationEntityTypeForm.
 */
class EvaluationEntityTypeForm extends EntityForm {

  /**
   * {@inheritdoc}
   */
  public function form(array $form, FormStateInterface $form_state) {
    $form = parent::form($form, $form_state);

    $evaluation_type = $this->entity;
    $form['label'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Label'),
      '#maxlength' => 255,
      '#default_value' => $evaluation_type->label(),
      '#description' => $this->t("Label for the Evaluation type."),
      '#required' => TRUE,
    ];

    $form['id'] = [
      '#type' => 'machine_name',
      '#default_value' => $evaluation_type->id(),
      '#machine_name' => [
        'exists' => '\Drupal\camp_evaluator\Entity\EvaluationEntityType::load',
      ],
      '#disabled' => !$evaluation_type->isNew(),
    ];

    /* You will need additional form elements for your custom properties. */

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function save(array $form, FormStateInterface $form_state) {
    $evaluation_type = $this->entity;

    $status = $evaluation_type->save();

    switch ($status) {
      case SAVED_NEW:
        drupal_set_message($this->t('Created the %label Evaluation type.', [
          '%label' => $evaluation_type->label(),
        ]));
        break;

      default:
        drupal_set_message($this->t('Saved the %label Evaluation type.', [
          '%label' => $evaluation_type->label(),
        ]));
    }
    $form_state->setRedirectUrl($evaluation_type->toUrl('collection'));
  }

  protected function actionsElement(array $form, FormStateInterface $form_state) {
    $actions = parent::actionsElement($form, $form_state); // TODO: Change the autogenerated stub

    //unset($actions['delete']);
    return $actions;
  }
}
