<?php

/**
 * Contains \Drupal\payment\Plugin\Payment\Method\BasicOperationsProvider.
 */

namespace Drupal\camp_finances\Plugin\Payment\Method;

use Drupal\payment\Plugin\Payment\Method\PaymentMethodConfigurationOperationsProvider;

/**
 * Provides payment_basic operations based on config entities.
 */
class OmniPayOperationsProvider extends PaymentMethodConfigurationOperationsProvider {

  /**
   * {@inheritdoc}
   */
  protected function getPaymentMethodConfiguration($plugin_id) {
    $entity_id = substr($plugin_id, strlen('payment_omnipay:'));

    return $this->paymentMethodConfigurationStorage->load($entity_id);
  }

  public function getOperations($plugin_id) {
    return parent::getOperations($plugin_id); // TODO: Change the autogenerated stub
  }
}
