version: 2
jobs:
  build:
    working_directory: /var/www
    docker:
      - image: circleci/php:7.1-apache-node-browsers
        environment:
          - DRUSH_VERSION: 8.1.13
          - DRUPAL_CONSOLE_VERSION: 1.0.2
          - PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.composer/vendor/bin:/usr/local/go/bin"
          - SITE_URL: "http://web"
          - PHP_INI_PATH: "/usr/local/etc/php/conf.d"
      - image: circleci/mysql:5.6-ram
        environment:
          - MYSQL_ROOT_PASSWORD: root
      - image: selenium/standalone-chrome
        environment:
          # Need in order to bypass the fact that Xvfb is already running on the current machine.
          - DISPLAY: ":98.0"
    steps:
      - run:
          name: Add web to Host File
          command: |
            echo "127.0.0.1 web" | sudo tee -a /etc/hosts;
            echo "127.0.0.1 browser" | sudo tee -a /etc/hosts;
            echo "127.0.0.1 db" | sudo tee -a /etc/hosts;
      - run:
          name: Test Selenium Is Running
          command: |
            sleep 5;
            ps aux;
            netstat -ant;
            curl -X POST -H "Content-type: application/json;" -d '{"desiredCapabilities":{"browserName":"chrome","platform":"MAC"}}' http://web:4444/wd/hub/session;
      - run:
          name: Cleanup Existing HTML folder
          command: sudo chown -R circleci /var/www/
      - checkout:
          path: /var/www/camp
      - run:
          name: Local Fix
          command: |
            if [ ! -d /var/www/camp ]; then
              sudo mv /var/www /var/camp;
              sudo mkdir /var/www/;
              sudo mv /var/camp /var/www/camp;
              sudo chown -R circleci /var/www;
            fi
      - run:
          name: Apache & PHP Configurations
          command: |
            sudo a2enmod rewrite;
            sudo apache2ctl -M;
            sudo cp camp/.circleci/apache.conf /etc/apache2/sites-available/000-default.conf;
            echo 'memory_limit = 2G' | sudo tee -a ${PHP_INI_PATH}/drupal.php.ini;
            echo 'max_execution_time = 120' | sudo tee -a ${PHP_INI_PATH}/drupal.php.ini;
            echo 'sendmail_path = /bin/true' | sudo tee -a ${PHP_INI_PATH}/drupal.php.ini;
      - run:
          name: Install Server Tools
          command: |
            sudo apt-get install mysql-client jq imagemagick;
            sudo apt-get update >/dev/null;
            sudo apt-get --force-yes --install-recommends install \
              g++ \
              libfreetype6-dev \
              libgpgme11-dev \
              libicu-dev \
              libglib2.0-0=2.42.1-1+b1 \
              libglib2.0-bin=2.42.1-1+b1 \
              libjpeg62-turbo-dev \
              libglib2.0-dev \
              librsvg2-dev \
              libmagickcore-6.q16-dev \
              libmagickwand-6.q16-dev \
              libmagickcore-dev \
              libmagickwand-dev \
              libmcrypt-dev \
              libmhash-dev \
              libpng12-dev \
              libxslt1-dev \
              zlib1g-dev \
              apt-utils \
              libfreetype6 \
              libgpgme11 \
              libicu52 \
              libjpeg62-turbo \
              libmagickcore-6.q16-2 \
              libmagickwand-6.q16-2 \
              libmcrypt4 \
              libmhash2 \
              libpng12-0 \
              libxslt1.1 \
              zlib1g;
            sudo docker-php-ext-configure gd;
            sudo docker-php-ext-install >/dev/null -j$(nproc) \
              bcmath \
              bz2 \
              calendar\
              dba \
              exif \
              gd \
              gettext \
              intl \
              mcrypt \
              opcache \
              pcntl \
              mysqli \
              pdo_mysql \
              shmop \
              soap \
              sockets \
              sysvmsg \
              sysvsem \
              sysvshm \
              wddx \
              xsl \
              zip;
            sudo pecl update-channels;
            sudo pecl install >/dev/null </dev/null \
              gnupg \
              imagick;
            sudo docker-php-ext-enable gnupg imagick;
      - run:
          name: Start Apache
          command: sudo apache2-foreground
          background: true
      - run:
          name: Installing Drupal Tools
          command: |
            composer global require hirak/prestissimo drupal/coder;
            phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer;
            ln -s ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Drupal;
            ln -s ~/.composer/vendor/drupal/coder/coder_sniffer/DrupalPractice ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/DrupalPractice;
            git clone git://git.drupal.org/sandbox/coltrane/1921926.git ~/.drush/DrupalSecure;
            ln -s ~/.drush/DrupalSecure/DrupalSecure ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/DrupalSecure;
            sudo curl -sSL "https://github.com/hechoendrupal/drupal-console-launcher/releases/download/${DRUPAL_CONSOLE_VERSION}/drupal.phar" -o /usr/local/bin/drupal;
            sudo curl -sSL "https://github.com/drush-ops/drush/releases/download/${DRUSH_VERSION}/drush.phar" -o /usr/local/bin/drush;
            sudo chmod +x /usr/local/bin/*;
            drush dl registry_rebuild --default-major=7 --destination=$HOME/.drush >/dev/null;
            drush cc drush;
      - run:
          name: Drupal Tools Version Check
          command: |
            phpcs --version;
            phpcs -i;
            drupal --version;
            drush --version;
      - run:
          name: Setup Drupal
          command: |
            cp camp/composer.json ./;
            mkdir -p docroot/profiles/contrib;
            mv camp docroot/profiles/contrib/;
            composer install --ansi;
            jq '.["extra"]["merge-plugin"]["require"] += ["docroot/profiles/contrib/camp/composer.json"]' composer.json > composer.json.new;
            mv composer.json.new composer.json;
            composer update --lock;
            sudo chmod -R 777 /var/www/docroot;
            mkdir -p docroot/sites/default/files;
            mkdir -p docroot/themes;
            sudo cp -f /var/www/docroot/profiles/contrib/camp/.circleci/settings.* /var/www/docroot/sites/default/;
            sudo chown -R www-data:www-data /var/www/;
      - run:
          name: Verify Site is Running
          command: curl -i $SITE_URL
      - run:
          name: Run Behat Installer Tests
          command: ../../../../bin/behat --config behat.camp-install.yml --tags "@install" --colors --format progress -vvv
          working_directory: docroot/profiles/contrib/camp
      - run:
          name: Drush Truncate Database (Start Fresh)
          working_directory: docroot
          command: drupal database:drop default --yes
      - run:
          name: Remove settings file
          command: sudo rm -rf sites/default/settings.*
      - run:
          name: Run Drupal Site Install
          working_directory: docroot
          command: |
            sudo drupal site:install camp \
              --yes \
              --site-name="Camp Website" \
              --site-mail="admin@example.com" \
              --account-name="Admin" \
              --account-mail="admin@example.com" \
              --account-pass="admin" \
              --langcode="en" \
              --db-type="mysql" \
              --db-host="db" \
              --db-port="3306" \
              --db-name="circle_test" \
              --db-user="root" \
              --db-pass="root";
            sudo chown -R www-data:www-data sites/default;
      - run:
          name: Run PHPUnit Tests
          command: ../../../../bin/phpunit --colors="always"
          working_directory: docroot/profiles/contrib/camp
      - run:
          name: Run Behat Tests
          command: ../../../../bin/behat --tags "~@install" --colors --format progress;
          working_directory: docroot/profiles/contrib/camp
      - store_artifacts:
          path: docroot/profiles/contrib/camp/tests/behat/reports
      - store_artifacts:
          path: docroot/profiles/contrib/camp/tests/behat/screenshots
