<?php

namespace Drupal\camp\Form;

use Drupal\camp\CampInstallerPluginManager;
use Drupal\Core\Extension\InfoParserInterface;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslationInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\camp\CampInstallerInterface;

/**
 * Defines form for selecting extra components for the assembler to install.
 */
class AssemblerForm extends FormBase {

  /**
   * The Camp Installer Feature manager
   * @var \Drupal\camp\CampInstallerPluginManager
   */
  protected $campFeatureManager;

  /**
   * @var array|mixed[]|null
   */
  protected $features;

  /**
   * @var array|mixed[]|null
   */
  protected $plugins;

  /**
   * Constructor.
   *
   * @param \Drupal\camp\CampInstallerPluginManager $campFeatureManager
   */
  public function __construct(CampInstallerPluginManager $campFeatureManager) {
    $this->campFeatureManager = $campFeatureManager;
    $this->features = $this->campFeatureManager->getDefinitions();
    foreach ($this->features AS $feature => $feature_info) {
      $plugin = $this->campFeatureManager->createInstance($feature);
      $this->plugins[$feature] = [
        'info' => $feature_info,
        'plugin' => $plugin,
      ];
    }
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'camp_extra_components';
  }

  /**
   * {@inheritdoc}
   *
   * @return array
   *   Extra compoments modules.
   */
  public function buildForm(array $form, FormStateInterface $form_state, array &$install_state = NULL) {
    $form = array();

    $form['#title'] = $this->t('Configure Features');
    foreach ($this->plugins AS $feature => $feature_info){
      /** @var \Drupal\camp\CampInstallerBase $plugin */
      $plugin = $feature_info['plugin'];
      $feature_form = $plugin->buildForm(array(), $form_state) ?: array();
      if(count($feature_form) > 0) {
        $form[$feature] = [
          '#type' => 'details',
          '#title' => $feature_info['info']['title'],
          '#tree' => TRUE,
          '#description' => $feature_info['info']['description'],
          '#open' => FALSE,
        ];
        $form[$feature] = array_merge($form[$feature], $feature_form);
      }
    }

    $form['actions'] = [
      'continue' => [
        '#type' => 'submit',
        '#value' => $this->t('Assemble and install'),
        '#button_type' => 'primary',
      ],
      '#type' => 'actions',
      '#weight' => 5,
    ];

    return $form;
  }

  public function validateForm(array &$form, FormStateInterface $form_state) {
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    foreach ($this->plugins AS $feature => $feature_info){
      /** @var \Drupal\camp\CampInstallerBase $plugin */
      $plugin = $feature_info['plugin'];
      $plugin->validateForm($form, $form_state);
    }
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    foreach ($this->plugins AS $feature => $feature_info){
      /** @var \Drupal\camp\CampInstallerBase $plugin */
      $plugin = $feature_info['plugin'];
      $plugin->submitForm($form, $form_state);
    }
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('plugin.manager.camp_installer')
    );
  }
}